OOP版ボウリングプログラムの課題を提出
umizaru/ruby-practices pull request #10
Opened 2023-02-17 02:36 UTC by umizaru

オブジェクト指向版ボウリングプログラムの課題を提出します。
ご確認のほどよろしくお願いいたします。

- 各スコアでの点数出力
![スクリーンショット 2023-02-16 21 10 33](https://user-images.githubusercontent.com/57088113/219534864-dbfacb95-030b-4b6d-b023-1e975e3b395d.png)

- rubocop, test-unit
![スクリーンショット 2023-02-17 11 28 16](https://user-images.githubusercontent.com/57088113/219534828-3506164c-08e1-4f11-a1c9-dafa5b59bf5b.png)

2023-02-22 16:44 UTC, u1tnk requested changes

2023-02-22 16:44 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def initialize(frame)
frame変数に入っているのは Frameクラスのインスタンスを期待しますので、名前を工夫しましょう。

2023-02-22 16:44 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    10.times do |index|
`@frames`は10個になっているはずなので `@frames.each`を使う方がrubyらしいですね。

2023-02-22 16:44 UTC, u1tnk commented on 07.bowling_object/game.rb
> +  def build_frames
build_framesという名前は良いのですが、この名前なら Frameクラスのインスタンスの配列を作るべきです。

このままなら 「pinfallsの分割」ですね。
メソッド名の変更をするのも手ですが、分割してれば Frameクラスのインスタンスも作れるはずなので、ここで作ると良いでしょう。

2023-02-22 16:44 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      following_frames = @frames[index.succ..]
ここも following_framesであれば Frameクラスのインスタンスの配列と思います。

2023-02-22 16:44 UTC, u1tnk commented on 07.bowling_object/shot.rb
> +    pinfall == 'X' ? 10 : pinfall.to_i
ここで Xを10に解決する処理があるのに 各所で Xをチェックしているのはやめましょう。10にするのは Shotクラスの責務で strikeの判定は Frameクラスの責務です。

2023-02-22 16:46 UTC, u1tnk commented
大枠の仕組み、クラス構成などはできていますが、細かいところを色々指摘したので見てみてください。

2023-02-25 03:01 UTC, umizaru commented on 07.bowling_object/frame.rb
> +  def initialize(frame)
first~thirdのshotを生成しているので```frame```を```shot```に修正しました。

2023-02-25 03:17 UTC, umizaru commented on 07.bowling_object/game.rb
> +    10.times do |index|
```frames.each_with_index```を使うコードに修正しました。

2023-02-26 02:59 UTC, umizaru commented on 07.bowling_object/game.rb
> +  def build_frames
Frameクラスで```build_frames```するように修正しました。

2023-02-26 02:59 UTC, umizaru commented on 07.bowling_object/game.rb
> +      following_frames = @frames[index.succ..]
同じく、Frameクラスで処理するように修正しました！

2023-02-26 03:02 UTC, umizaru commented on 07.bowling_object/shot.rb
> +    pinfall == 'X' ? 10 : pinfall.to_i
```calc_bonus_point```のインスタンスメソッドで、Shotクラスを呼び出すように修正しました。

2023-02-28 14:06 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    10.times do |index|
> ちなみにここで言う「rubyらしさ」とは、何らかの意味を持つ数値（＝マジックナンバー？、このコードでいう10）はなるべく使わないようにする、ということでしょうか。

あー、ちょっと言葉足らずでしたね。
「rubyらしい」=「rubyを書く人が見なれた、分かりやすい書き方」というニュアンスでした。
ループ系は無限ループなどの特殊な場合を除いて、each/mapなどの Enumerator の機能を使ったシンプルなコードがrubyで良く見る書き方ですね。

2023-02-28 14:15 UTC, u1tnk commented on 07.bowling_object/game.rb
> +  def build_frames
ちょっと誤解されてますね。

場所の問題では無く、 

>  Frameクラスのインスタンスの配列を作るべき

という意味です。
もうちょっと具体的に書くと

`Frameクラスのインスタンス` は `Frame.new`したものです。

オブジェクト指向プログラミングの場合(rubyは「[オブジェクト指向スクリプト言語 Ruby](https://www.ruby-lang.org/ja/) 」なので普通はオブジェクト指向になります)、xxx_frames という名前のメソッドや変数を見たとき、Frameクラスが存在すればFrameクラスのインスタンスが入っているものと期待します。
なので pifallsの配列を返すのであれば xxx_pinfallsとした方が良いです。pinfallクラスは存在しないのでpinfallを表す数値か文字列が入っているものと伝わるでしょう。

ただ、ここで pinfallsの配列を返すよりも Frameクラスのインスタンスを返した方が分かりやすいし、pinfallの配列があればFrameクラスのインスタンスはできるはずなので、内容の方を変えることをオススメします。

2023-02-28 14:16 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      following_frames = @frames[index.succ..]
こちらも同じく、変数名と内容のズレについて指摘していたのでちょっと違います。
ついでに言うと 複数のframeにまたがるデータについてGameクラスに存在するのはおかしくありません。FrameクラスのクラスメソッドとするかGameクラスのインスタンスメソッドのどちらかが良いと思います。

2023-02-28 14:20 UTC, u1tnk requested changes

2023-02-28 14:20 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +        if frame.size == 2 || pinfall == 'X'
https://github.com/umizaru/ruby-practices/pull/10/files#r1114638909 のコメントはここも対象としていました。
Shotクラスで解決できる以上、その一箇所以外に存在するのは良くありません。

pinfall(文字列)の情報はShotクラスのインスタンスも持っており、できることが多いので、できるだけ早くShotクラスのインスタンスを作って、そちらを保持するようにすれば良いと思います。

2023-03-12 14:11 UTC, umizaru commented
たいへんお待たせしました、修正しましたのでご確認のほどよろしくお願いします！
<img width="667" alt="スクリーンショット 2023-03-12 23 07 03" src="https://user-images.githubusercontent.com/57088113/224550166-c252a55e-c4bd-4267-934a-80b889311650.png">

2023-03-12 15:51 UTC, u1tnk requested changes
もうちょっとですね！ 💪

2023-03-12 15:51 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      shot = Shot.new(pinfall).score
ここのshotとframeが名前と中身が合っていません。
また、せっかくShotインスタンスにしているのであればそのまま持っていて、Frameのinitializeではそのまま保存すれば良いと思います。
基本的にscoreの数値よりもShotインスタンスの方が情報量が多いのでscoreの数値でできる事は全部できるし便利なはずです。

2023-03-12 15:51 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      frames << Frame.new(frame) if frame.sum < 10 && frame.size == 2 || frame.size == 3
これは最後のframeですよね？そうであればループが終わった後にframeに残っていたものでFrameインスタンスを作れば良さそうな気がしましたがどうでしょうか？

2023-03-13 11:31 UTC, watsuki-hi commented on 07.bowling_object/frame.rb
> +      frames << Frame.new(frame) if frame.sum < 10 && frame.size == 2 || frame.size == 3
はい、こちら最後のframeでして、
> ループが終わった後にframeに残っていたものでFrameインスタンスを作れば良さそう

修正したところばっちり動きました…！

最後のフレームにも分岐処理をせねばと先入観を持ってしまっていましたが、
コードもシンプルにできて読みやすくなったと思います！

2023-03-13 13:11 UTC, umizaru commented on 07.bowling_object/frame.rb
> +      shot = Shot.new(pinfall).score
shotとframe、実体に合わせた名前に修正しました。
続いてShotインスタンスを生成している点でコードを以下のように修正したのですが、
``` ruby
  def self.build_frames(pinfalls)
    frames = []
    current_frame_shots = []
    pinfalls.each do |pinfall|
      shot = Shot.new(pinfall)
      current_frame_shots << shot
      if frames.size < 9 && (current_frame_shots.size == 2 || shot.score == 10)
        frames << current_frame_shots
        current_frame_shots = []
      end
    end
    frames << current_frame_shots
    binding.break
  end
end
```
これで意図した内容になっているでしょうか？
Frameインスタンスを生成せず、Shotインスタンスをそのままframesに入れる処理にしています。

また、このコードでframesを確認してみると以下のようになることが分かりました。

![スクリーンショット 2023-03-13 21 55 56](https://user-images.githubusercontent.com/57088113/224709066-04b88c76-4b4f-4cbb-addf-5cb8533a0678.png)

Shotインスタンスがフレームで分けられており意図したものにはなっているように思うのですが、そうするとGameクラスにあるFrameクラスの各種メソッド（calc_score,strike?,spare?など）が動かなくなるようになるかと思います。framesに合わせる形でGameクラスのコードも修正していくべきでしょうか？

2023-03-13 15:13 UTC, u1tnk requested changes

2023-03-13 15:13 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      shot = Shot.new(pinfall).score
良さそうです！ `current_frame_shots ` あたりとても何が入っている変数か分かりやすくなったと思います 👍 

> Frameクラスの各種メソッドが不要になりGameクラスも大きく修正することになるため、このまま進めていいものか迷っています。

見てみましたが、そんなに変更無いような気がしました。
単純な変更にするなら first_shotなどを取得可能にして frame.first_shot.score で良いですし、first/second_shot のscoreしか要らないと思うので Frame#first_score とかを作っても良いですね。

どっちにしても10行も無さそうな気がしますがどうでしょう？

2023-03-13 15:13 UTC, u1tnk commented on 07.bowling_object/shot.rb
> +  end
せっかく Xをそのまま保持しているので `strike?`を作るともっと綺麗になるかなと思いました。

2023-03-14 13:35 UTC, watsuki-hi commented on 07.bowling_object/frame.rb
> +      shot = Shot.new(pinfall).score
Frameクラスにfirst/second_shotなどのクラスメソッドを追加しました。
これで正しいか分からないのですがどちらかと言うとGameクラスよりもFrameクラスに修正が入りました。

Frameクラスが、
・インスタンス変数を使わなくなったので削除
・メソッドがクラスメソッドのみ
と少し異質なようにも思うのですが修正に問題はないでしょうか。

2023-03-14 13:38 UTC, watsuki-hi commented on 07.bowling_object/shot.rb
> +  end
迷ったのですが、Frameクラスで```strike?```を作りました。
```spare?```も必要なのですが、Shotクラスで```spare?```することはできないでは、
ならば、Frameクラスで両方作ったほうが分かりやすいはず、と考えたからです。

2023-03-14 13:40 UTC, umizaru commented
修正しました！度々ですがご確認のほどよろしくお願いします。

![スクリーンショット 2023-03-14 22 40 00](https://user-images.githubusercontent.com/57088113/225019212-b599369b-1f3a-47ad-8d40-4ddd05866719.png)

2023-03-14 15:18 UTC, u1tnk commented on 07.bowling_object/shot.rb
> +  end
ちょっと誤解されているかもしれません。
 もちろんspare?は実装できませんが、 `X` は必ずストライクなので実装可能です。
プラクティスのサンプルでもspareで10本のときは `0,10`になっていますので。

2023-03-14 16:14 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      shot = Shot.new(pinfall).score
いえ、これは良くないですね。

もしかして ` Frame#first_score` と私が書いたのをクラスメソッドと誤解されたでしょうか？

その前提で書くと `Frame#first_score`は Frameクラスのインスタンスメソッドで `first_score`を作るという意味です。
https://docs.ruby-lang.org/ja/latest/class/Enumerable.html こういうrubyのドキュメントで#で検索してみれば出てくるので標準的な記法です。

> Frameクラスの各種メソッドが不要になり

確かに書いてますが、first_shotなどが単にShotインスタンスを返すなら attr_readerで良くなるので無くなるという意味かと思っておりました。なので修正部分も10行も無いと思っていたのですが…確認頂いたのに意図が分かっておらず申し訳無いです。

と、ここまで書いていてやっと分かりました。 [Shotインスタンスを先に作った方が良いということからFrameクラスに渡すこともやめたという事でしょうか？

私のイメージは以下のようにFrameクラスのinitializeにShotインスンタンスを渡すものでした。後は元のFrameクラスと大差無いと思います。

```
class Frame
  def initialize(first_shot, second_shot, third_shot)
    @first_shot = first_shot
    @second_shot = second_shot
    @third_shot = third_shot
  end
......
```

意図伝わりますでしょうか？

2023-03-15 13:51 UTC, watsuki-hi commented on 07.bowling_object/frame.rb
> +      shot = Shot.new(pinfall).score
詳細解説、ありがとうございます…。
はい、```Frame#first_score```をインスタンスメソッドではなく、クラスメソッドと誤解してしまっていました。
また、もともとFrameクラスのinitializeで書いていた、
```
class Frame
  def initialize(shots)
    @first_shot = Shot.new(shots[0])
    @second_shot = Shot.new(shots[1])
    @third_shot = Shot.new(shots[2])
  end
```
の```initialize(shots)```には["6","2","1"]のような文字列の配列を入れねば、そして、
```Shot.new(shots[X])```をそのまま活かさねば、と考えてしまい、
ShotクラスのインスタンスをそのままFrameクラス（のinitialize）に入れるところまで考えが及びませんでした。
こちら踏まえFrameクラス、Gameクラスを修正しましたのでご確認いただけますでしょうか。

2023-03-15 13:53 UTC, watsuki-hi commented on 07.bowling_object/shot.rb
> +  end
失礼しました、Shotクラスでstrike?を実装しました！

2023-03-15 16:13 UTC, u1tnk requested changes

2023-03-15 16:13 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    @frame = frame
`frame`という名前に  Frameインスタンス以外を入れないようにしましょう。
何度も書きますが、 `hogeという名前の変数があり、 Hogeというクラスがあるときは Hogeのインスタンスが入っているべき`  なので。

また、 ` @frame`と `@xxx_shot`に同じ内容が分けて格納されていて良くないです。

 今 frame変数には shotの配列が入っていますのでその変数名は何が良いでしょう？

また、ここは混乱しそうなので言ってしまうと、その「Shotインスタンスの配列」だけ持っていれば良いです。配列には順番の情報もあるので。

2023-03-15 16:13 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    frame_score = 0
オブジェクト指向とは関係無いですが、ここは Arrayクラスのメソッドを眺めるともっと綺麗に書く方法が見つかると思います 💪

2023-03-15 16:13 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    frames << current_frame_shots
このframesも同様です。

2023-03-15 16:16 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      game_score += Frame.new(frame).calc_frame_score
これ以前指摘した `Shot.new(pinfall).score` と同じでクラスをただのメソッドとして使っているので良くないとしたものと同じです。

2023-03-22 12:14 UTC, watsuki-hi commented on 07.bowling_object/frame.rb
> +    @frame = frame
shotの配列が入っていることを表すために、Frameクラスのインスタンス変数を```frame_shots```のみにしました。
また、この箇所の他にも、Shotクラスのインスタンスが入っているのに変数がframeとなっている箇所があったので合わせて修正しました。

2023-03-22 12:14 UTC, umizaru commented on 07.bowling_object/frame.rb
> +    frame_score = 0
Array#mapメソッドを使って短いコードに修正しました！

2023-03-22 12:15 UTC, umizaru commented on 07.bowling_object/frame.rb
> +    frames << current_frame_shots
同じく変数名を修正しました。

2023-03-22 12:17 UTC, umizaru commented on 07.bowling_object/game.rb
> +      game_score += Frame.new(frame).calc_frame_score
インスタンスを変数```current_frame_shots```に入れてから、
変数に対してメソッドを使う処理に修正したのですが合っているでしょうか。

2023-03-22 16:17 UTC, u1tnk requested changes
もう少しですね！
複数箇所修正する必要はありますが、やることはFrameインスタンスの扱い方の一つだけだと思います 💪

2023-03-22 16:17 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def self.build_frames(pinfalls)
framesをbuildするのでreturnするものは frameの配列です。
shotsをframeごとに分割できているので、そこで`Frame.new(shots)`して保存してしまえば良いです。

2023-03-22 16:17 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      current_frame_shots = Frame.new(frame_shots)
これだと単に 二行に分けただけなのでやはりFrameクラスをメソッドとして使っているだけになってしまっています。
Shotと同じようにFrameも作れる情報が揃ったらFrameインスタンスを作って、それを保持して各所で使うようにすれば良いです。
複数箇所で shotsからFrame.newして使っていますが、それを一箇所にすれば良いです。

2023-03-26 08:54 UTC, umizaru commented on 07.bowling_object/frame.rb
> +  def self.build_frames(pinfalls)
こちらFrame.new(current_frame_shots)するように修正しました！

1点、分からない点があるのですが質問させてください。
上記のように修正したあと```binding.break```で```frame_shots```を見てみると以下のようになっています。

![スクリーンショット 2023-03-26 17 37 38](https://user-images.githubusercontent.com/57088113/227764936-91392802-1626-48f4-9f56-07383065aa69.png)

frame_shotsについて、
・frame_shotsは配列であり各要素にFrameインスタンスを持っている。
・また、Frameインスタンスは```@frame_shots```をインスタンス変数に持ち、
・```@frame_shots```はShotインスタンスを持つ。
と理解しているのですが、
そうすると、frame_shotsはFrameインスタンスとShotインスタンスの両方の情報を持つことになるかと思います。

「frame_shotsはFrameインスタンスを持っている」とするならば、
変数名もそれに倣ったもの（例えばframesなど）に修正が必要かと考えたのですが合っているでしょうか。

それが正しいならば、Gameクラスの```@all_frame_shots```や```next_frame_shots```なども修正が必要かと思っています。

2023-03-26 09:20 UTC, umizaru commented on 07.bowling_object/game.rb
> +      current_frame_shots = Frame.new(frame_shots)
Gameクラスのインスタンス変数を使うよう修正しました。

2023-03-26 13:28 UTC, u1tnk commented on 07.bowling_object/shot.rb
> +    @shot = shot
すみません、だいぶ前からだと思うのですが Shotクラス内なので shotとか `@shot`とかを使うのは良くないですね。
Gameでは `pinfall`という名前を使っているのでここでも同様にしましょう。

2023-03-26 13:28 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def self.build_frames(pinfalls)
> それが正しいならば、Gameクラスの@all_frame_shotsやnext_frame_shotsなども修正が必要かと思っています。

はい、そのつもりで指摘しました。
基本的に 

- Game
    - Frame
        - Shot
            - pinfall

という構造(Gameはframesを持ち、Frameは shotsを持ち Shotはpinfallを持つ)になっています。
Gameがshotの情報を欲しいときはFrameに「一投目のshot(のscore)をくれ」と言えばもらえるというように自分が直接持っているインスタンスにお願いしてもらうようにしましょう。

GameがShotを直接管理しないことで独立性を高めることができます。

2023-03-26 13:59 UTC, umizaru commented on 07.bowling_object/shot.rb
> +    @shot = shot
```shot```を```pinfall```に修正しました！

2023-03-29 01:19 UTC, u1tnk requested changes
もうほぼオッケーですね！

あと細かいところではありますが、bonus/point/scoreでスコアを表す数値のsuffixがゆれてるのでそこを合わせてください。

2023-03-29 13:38 UTC, umizaru commented
ありがとうございます！たしかにですね、考慮できていなかったです。
スコアに関するメソッド名と変数名のsuffix（接尾語の意味なんですね）を```score```に統一しました。

2023-03-30 11:13 UTC, u1tnk approved these changes
最後の suffixの統一のところ、 strike_score だと strikeの基本部分も足されるのか迷うので strike_bonus_scoreの方が良かったかなと思いました。

とはいえ、ほぼ細かいところなのでオッケーです！

2023-03-30 13:23 UTC, umizaru commented
たしかに…！！```strike/spare_bonus_score```に修正して提出します。

2023-03-30 13:25 UTC, merged