lsプログラムを作成
umizaru/ruby-practices pull request #4
Opened 2022-09-22 16:27 UTC by umizaru

2022-09-28 15:36 UTC, u1tnk requested changes

2022-09-28 15:36 UTC, u1tnk commented on 05.ls/ls.rb
> +rows = 3 # 列数
rowが行でcolumnが列なので逆かと思います。
また、逆になったとして columnsが列の数でrowsが一行分のデータとすると、名前が並列なもの(同種なもの)に見えるのに中身が全然違うという事に違和感があるので名前を再検討してみてください。

2022-09-28 15:36 UTC, u1tnk commented on 05.ls/ls.rb
> +display_array.map do |n|
mapは配列から別の配列を作るメソッドなので、返り値が不要なときはeachを使いましょう。

2022-09-28 15:36 UTC, u1tnk commented on 05.ls/ls.rb
> +  display_array << current_dir_files.values_at(i, i + columns, i + columns * 2)
display_arrayに格納して、その後で そのまま表示するだけなのであれば、格納せず、ここで表示すれば良いと思います。

2022-10-01 02:58 UTC, umizaru commented on 05.ls/ls.rb
> +rows = 3 # 列数
rowsとcolumnsの配置を入れ替えるとともに、
変数名をdata_of_rows, number_of_columnsに修正しました。

2022-10-01 02:59 UTC, umizaru commented on 05.ls/ls.rb
> +display_array.map do |n|
mapをeachに修正しました。

2022-10-01 03:00 UTC, umizaru commented on 05.ls/ls.rb
> +  display_array << current_dir_files.values_at(i, i + columns, i + columns * 2)
display_arrayは消去し、
.join(' ')メソッドを最後尾に配置して1文でファイル名を表示させるよう修正しました。

2022-10-02 14:54 UTC, u1tnk approved these changes
データが入っているのは普通なので`data_of_rows ` は `rows`で良いと思います。
それだけなのでOKです！

2022-10-04 14:42 UTC, u1tnk requested changes
まず、前回の ls1と同じブランチで開発してると思いますが、差分が分からないので、前回のものはマージしてしまって、ブランチは新しいものに分けて欲しいです 🙏 

その他コメントしてるので確認お願いします 🙏

2022-10-04 14:42 UTC, u1tnk commented on 05.ls/ls.rb
> +opt = ARGV.getopts('a', 'l', 'r')
[プログラミング初心者は変数名やメソッド名を略さない方がいいよ、という話 - give IT a try](https://blog.jnito.com/entry/2020/10/20/092724)

という事で略さないようにしましょう。
ruby界隈だと単数、複数は大事にするので複数形にする必要もあります。

2022-10-04 14:42 UTC, u1tnk commented on 05.ls/ls.rb
> +array = opt.values
hashのままの方が opt["a"]のように使えて `array[0]`よりも情報量が多いので配列にする事は無いです。
また、変数名が 何の配列なのか？ということが分からないのでよくないです。
また、前述しましたが複数形かどうかで配列かを判別する文化なので arrayとか xxx_arrayとかは使わないようにしましょう。

2022-10-04 14:42 UTC, u1tnk commented on 05.ls/ls.rb
> +  if array[0].to_s == 'true'
これ文字列にして比較していますが、元がboolean型なので

```
if array[0]
```

だけと同じなので、なるべくシンプルにしましょう。

2022-10-04 14:42 UTC, u1tnk commented on 05.ls/ls.rb
> +    Dir.glob(['*', '.*'])
ローカルで実行したところ

![image](https://user-images.githubusercontent.com/279240/193848994-4b984a8f-f015-4f49-8aaa-20eb599a8c25.png)

と差異があります。`..`はプラクティスにあるように出なくても良いですが、順番は一致して欲しいです。

2022-10-04 14:42 UTC, u1tnk commented on 05.ls/ls.rb
> +data_of_rows = (number_of_files.to_f / number_of_columns).ceil
前回のプラクティスで `data_of_rows`は`rows`にしましょうと指摘したと思います。
前回のプラクティス的にはOKですが、次は修正してくださいという意図でしたので、修正お願いします。
ちょっとわかりづらくてすみません 🙏

2022-10-09 11:31 UTC, merged