lsコマンド2を作成
umizaru/ruby-practices pull request #5
Opened 2022-10-09 14:19 UTC by umizaru

2022-10-10 15:06 UTC, u1tnk requested changes

2022-10-10 15:06 UTC, u1tnk commented on 05.ls/ls.rb
> +argument = ARGV.getopts('a')
getoptsはオプションを取るものなので argumentでは無くオプションが入っているという変数名にすると良いですね。

2022-10-10 15:06 UTC, u1tnk commented on 05.ls/ls.rb
>  number_of_columns = 3
前のときに言い忘れてたと思います🙏 
こういう数値に名前を付けて絶対変えないものは定数となるので全部大文字にしましょう。

2022-10-11 11:07 UTC, umizaru commented on 05.ls/ls.rb
> +argument = ARGV.getopts('a')
引数とオプションがごっちゃになってましたね。
迷いましたがシンプルにoptionへ修正します。

2022-10-11 11:07 UTC, umizaru commented on 05.ls/ls.rb
>  number_of_columns = 3
すべて大文字に修正します！次回以降のプラクティスでも気を付けます。

2022-10-12 02:30 UTC, u1tnk requested changes
指摘した修正部分、このままだと動かない気がするのですが、動作確認はしましたでしょうか？

やっていないのでしたら、プログラミングは本当にささいな修正で大丈夫だろって思っても思わぬところで壊れるので毎回確認はするようにしましょう！

後の話ですが、こういう理由で自動テストが必要になるんです。

2022-10-12 02:30 UTC, u1tnk commented on 05.ls/ls.rb
> +width = current_dir_files.map(&:size).max + between_columns
小文字のままになっているようです。

2022-10-12 02:30 UTC, u1tnk commented on 05.ls/ls.rb
> +option = ARGV.getopts('a')
細かいですが、optionは複数入るはずなので複数形の方が良いですね。

2022-10-12 02:30 UTC, u1tnk commented on 05.ls/ls.rb
> +  if argument['a']
変数名が変わってるはずと思います。

2022-10-12 03:10 UTC, umizaru commented on 05.ls/ls.rb
> +width = current_dir_files.map(&:size).max + between_columns
大文字に修正しました。

2022-10-12 03:10 UTC, umizaru commented on 05.ls/ls.rb
> +option = ARGV.getopts('a')
option"s"と複数形に修正しました。

2022-10-12 03:10 UTC, umizaru commented on 05.ls/ls.rb
> +  if argument['a']
変数名をoptionsに修正しました。

2022-10-12 14:06 UTC, u1tnk approved these changes

2022-10-16 01:56 UTC, merged