ls4の課題を提出
umizaru/ruby-practices pull request #7
Opened 2022-10-21 13:47 UTC by umizaru

2022-10-21 14:57 UTC, u1tnk requested changes

2022-10-21 14:57 UTC, u1tnk commented on 05.ls/ls.rb
> +@current_dir_files = Dir.glob('*')
トップレベルでインスタンス変数を使うのはNGです。メソッド内で使うときは引数、返り値でやりとりするようにしてください。

2022-10-21 14:57 UTC, u1tnk commented on 05.ls/ls.rb
> +NUMBER_OF_FILESTAT.times do
まず、timesは `3.times do |i|`とブロック引数を入れればカウンタを自分で作る必要はないです。
ちなみにここを固定で9回くりかえしてるようですが、どういう意図でしょうか？

2022-10-21 14:57 UTC, u1tnk commented on 05.ls/ls.rb
> +@current_dir_files = Dir.glob('*')
メソッド定義とメイン処理が交互にでてきていて流れが分かりづらいです。

 メソッド定義するのであればメソッドだけ定義して、最後にそれを実行するようにしましょう。

2022-10-21 14:57 UTC, u1tnk commented on 05.ls/ls.rb
> +  file_permission = permission_number.gsub(/[01234567]/, PERMISSION_PATTERNS)
この挙動(gsub第二引数にhashを渡す)は知ら無かったですね。なるほど。

2022-10-26 10:18 UTC, umizaru commented on 05.ls/ls.rb
> +@current_dir_files = Dir.glob('*')
ガンガン使ってましたね…。引数でやり取りするようにメソッドを修正しました。

2022-10-26 10:20 UTC, umizaru commented on 05.ls/ls.rb
> +NUMBER_OF_FILESTAT.times do
固定の9回ですが、表示すべき属性の数（ファイルのパーミッションやファイル名、タイムスタンプなど）だと勘違いしていました。属性の数が9なので固定で9を入れればいいと。ですが実際はそうではなく、カレントディレクトリにあるファイルの数だけ繰り返す必要があると気づきましたので修正しました。

2022-10-26 10:21 UTC, umizaru commented on 05.ls/ls.rb
> +@current_dir_files = Dir.glob('*')
いちばん最後にメソッドを実行するように修正しました。

2022-10-27 14:26 UTC, u1tnk requested changes
mainにまとめるのはとても良いのですが、 -lと通常で完全に分かれるのはちょっと見づらいと思います。
あと、filestatから何かを取得するメソッドが多いせいで重複が多くて見づらくなっちゃっていますね。

ちょっと厳しめですが、ここで整理しておくと ls5とオブジェクト指向lsでラクになると思うので、整理したいと思います。

これだけだとどうして良いか分からないと思うので方針を書いてしまいます。
メイン処理を以下の大きく二つの処理に分けてみましょう。

1. データをまとめて整理する処理だけをする 、ファイル名ごとにfilestatやsizeなど必要な情報をまとめる 、まとめた結果以下のようなフォーマットのデータができるイメージ

```
[
  {file_name: "hoge.txt", size: 123, filestat: filestat}
  ....
]
```

2. 表示、整形だけをする。オプションlの分岐はここだけで良い

という事でmainだけをざっくり書くと以下みたいになります。名前は日本語にしておくので適切な名前にしてください。

```
def メイン
  ファイルデータ配列 =  データ収集、整理するメソッド
if options['l']
  詳細情報を表示(ファイルデータ配列 )
else
  ファイル名だけを表示(ファイルデータ配列 ) # ファイル名しか使わないが情報が多い分には問題無い
end
```

2022-10-27 14:26 UTC, u1tnk commented on 05.ls/ls.rb
> +def main_none(current_dir_files, number_of_files)
noneというのはちょっと分かりづらいです。 ファイル名のみを表示する…としたいところですがmainとなると全体なので名前がつけづらいですね。
全体にコメントしますが、機能ごとに分離していくと良いと思います。

2022-10-27 14:26 UTC, u1tnk commented on 05.ls/ls.rb
> +def each_data(current_dir_files, current_dir_path)
メソッド名が良くないです。 eachするためのdataという意図だと思いますが、メソッド名は何をやっているか？何が帰ってくるか？が分かる名前にしたいです。

2022-10-27 14:26 UTC, u1tnk commented on 05.ls/ls.rb
> +def all_data(current_dir_files, current_dir_path)
こちらも each_dataの内容をprintしているので、せめて printとか output をつけたいですね。

2022-10-27 14:26 UTC, u1tnk commented on 05.ls/ls.rb
> +def month_data(current_dir_files, current_dir_path)
month/minute/dayで重複が多いですね。
重複を減らすようにしてみましょう。filestatのみを保存しておいて表示するときに使うと良いのではと思います。

2022-11-04 14:18 UTC, u1tnk requested changes

2022-11-04 14:18 UTC, u1tnk commented on 05.ls/ls.rb
> +def options_none(file_names)
ここまで行かなかったですが、メソッド名が良くないです。

基本は `動詞_対象` で、メソッドが何をやっているか？をつけるべきです。なので`オプション無しのときの出力処理`なので、 そのまま書くとしても `print_files_when_option_none` となりますが、まあ、そもそもオプション無しイコール標準なので削るのが普通です。なので `print_files`とかでしょうか。

また、標準とかオプションを名前に付けるのでは無く、何をやっているか？に着目する方がより良いです。 
「オプションlのときの表示」ではなく「詳細形式の表示」という感じですね。
これは以下の理由からです。

- 何をやっているかが分かりやすい
- オプションじゃない方法(設定ファイルとか)で詳細表示をすることが現実ではあり得る(このプラクティスでは無いですが)

2022-11-04 14:18 UTC, u1tnk commented on 05.ls/ls.rb
> +PERMISSION_PATTERNS = { '0' => '---', '1' => '--x', '2' => '-w-', '3' => '-wx', '4' => 'r--', '5' => 'r-x', '6' => 'rw-', '7' => 'rwx' }.freeze
細かいところですが、横に長いとき(個人的には3つぐらい)は改行して一つ一行にした方が見やすいですね。

2022-11-04 14:18 UTC, u1tnk commented on 05.ls/ls.rb
> +      print_files_detail(file)
詳細表示の方は `print_files_detail`という名前なら同列の存在が `option_none`だとなおさらおかしいです。
同列の内容であれば同じルールで命名しましょう。

2022-11-05 10:06 UTC, u1tnk approved these changes

2022-11-05 10:06 UTC, u1tnk commented on 05.ls/ls.rb
> +  size = files.map { |x| x[:size] }
map使いこなしてますね 👍 

全然これで良いんですが、豆知識としてmaxにブロック渡すともっとスッキリしますよ。

2022-11-05 10:06 UTC, u1tnk commented on 05.ls/ls.rb
> +def stat_to_type_and_permission(stat)
教えるときに statから変換という意図で `stat_to_xxx`でサンプル書いちゃってて、これでも悪くは無いんですが

`type_and_permission(stat)`でも引数名と合わせれば十分分かるので、そちらで良いですね。
これも修正しなくても大丈夫です。

2022-11-05 14:22 UTC, merged