ls5の課題を提出
umizaru/ruby-practices pull request #8
Opened 2022-11-06 06:21 UTC by umizaru

lsコマンド5の課題を提出します。
前回から追加した処理は以下のとおりです。

・```-a```, ```-r```オプション
・文字幅の整列（```hardlink```, ```user```, ```group```, ```size```）
・月、時刻のゼロ表示を消す（09 → 9）
・一部メソッド名の修正

ご確認のほどよろしくお願いいたします。

2022-11-06 14:11 UTC, u1tnk requested changes

2022-11-06 14:11 UTC, u1tnk commented on 05.ls/ls.rb
> +  file_names = Dir.glob('*', File::FNM_DOTMATCH) if options['a']
optionが無いときは mainの外でfile_namesを取っているのにoptionがあるときだけここでやっているのが分かりづらいです。

2022-11-06 14:11 UTC, u1tnk commented on 05.ls/ls.rb
> +  width = identify_character_width(files)
ls4のときに見逃してたかもしれませんが、何のwidthなのか分かる名前にしましょう。

2022-11-07 13:33 UTC, umizaru commented on 05.ls/ls.rb
> +  file_names = Dir.glob('*', File::FNM_DOTMATCH) if options['a']
確かに！気づかなかったです！```if options['a']``` , ```if options['r']```を外に出しちゃいます！

2022-11-07 13:51 UTC, umizaru commented on 05.ls/ls.rb
> +  width = identify_character_width(files)
ls4のときにはこの変数は記述できていませんでした。
命名に具体性が欠けていました。```size```や```user```にあるデータの中で最大の文字数を返すので、
変数名を```maximum_number_of_characters```に修正しました。

2022-11-07 16:39 UTC, u1tnk approved these changes
コメントはしましたが十分なのでOKです！

2022-11-07 16:39 UTC, u1tnk commented on 05.ls/ls.rb
> +file_names = Dir.glob('*', File::FNM_DOTMATCH) if options['a']
十分なので修正不要ですが、ファイル探索は比較的(計算などに比べて)重い処理なので一回で済ませた方が良いですね。
(気づかない差と思うでしょうが、ファイル数が1000とかになると本当に遅いです)
ifで分岐してそれぞれ一回実行すると良いです。

2022-11-07 16:39 UTC, u1tnk commented on 05.ls/ls.rb
> +  maximum_number_of_characters = identify_maximum_number_of_characters(files)
情報が足りないのはNGですが、これもNGってほどじゃないけどちょっと長過ぎるかと思います。
`max_lengths`ぐらいで良いと思います。
number_of_characterは lengthとほぼ同じ意味ですし。最初は下手に略さない方が良いのですがmaximumをmaxと略すのは一般的(rubyのメソッド名もmaxですし)なので良いでしょう。

データ構造を工夫すればもっとシンプルに書けるのですが、ここでは十分なので修正不要です。
ここを綺麗にするのはobject指向版で頑張りましょう 💪

2022-11-08 12:48 UTC, merged